# Build GrpcServer
build-server:
	@dotnet build src/GrpcServer/GrpcServer.csproj

# Build GrpcClient
build-client:
	@dotnet build src/GrpcClient/GrpcClient.csproj

# Run GrpcServer
run-server: build-server
	@dotnet run --project src/GrpcServer/GrpcServer.csproj

# Run GrpcClient
run-client: build-client
	@dotnet run --project src/GrpcClient/GrpcClient.csproj

# Build both projects
build: build-server build-client
